[package]
name = "exmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sc = { version = "0.2.7"}

[build-dependencies]
bindgen = "0.63.0"
